let allNPC = ["1337mage43",
"1337sp34kr",
"50% Luke",
"? ? ? ?",
"A floating table",
"A'abla",
"Abbot Langley",
"Aberab",
"Abidor Crank",
"Abigaila",
"Abigale",
"Abyssal guardian (Guardians of the Rift)",
"Abyssal leech (Guardians of the Rift)",
"Abyssal orphan",
"Abyssal protector",
"Abyssal walker (Guardians of the Rift)",
"Account Guide",
"Account security tutor",
"Achietties",
"Acorn (NPC)",
"Adamantite ore (Blast Furnace)",
"Adventurer",
"Adventurer (easy)",
"Adventurer Jon",
"Advisor Ghrim",
"Aemad",
"Aeonisig Raispher",
"Afrah",
"Aga",
"Aggie",
"Agility Boss",
"Agility Instructor",
"Agility Trainer",
"Agmundi",
"Agnar",
"Ahab",
"Aisles",
"Aivas",
"Ajjat",
"Ak-Haranu",
"Ak-Haranu (2014 April Fools)",
"Akthanakos",
"Al Kharid Camel",
"Al Shabim",
"Al the Camel",
"Alain",
"Alan (Farming Guild)",
"Alchemy Guardian",
"Alec Kincade",
"Aleck",
"Alek Constantine",
"Alexander",
"Alexandra",
"Alfonse the waiter",
"Ali Morrisane",
"Ali the Barman",
"Ali the Camel",
"Ali the Camel Man",
"Ali the Carter",
"Ali the dyer",
"Ali the Farmer",
"Ali the Guard",
"Ali the Hag",
"Ali the Kebab seller",
"Ali the Leaflet Dropper",
"Ali the Mayor",
"Ali the Operator",
"Ali the Sandsweeper",
"Ali the Smith",
"Ali the Snake Charmer",
"Ali the Tailor",
"Alice",
"Alice the Camel",
"Alice's husband",
"Allanna",
"Almera",
"Alrena",
"Alry the Angler",
"Altarkiz",
"Aluft Gianne",
"Aluft Gianne snr.",
"Alviss",
"Alwyn",
"Alyssa",
"Ambassador Alvijar",
"Ambassador Ferrnook",
"Ambassador Gimblewap",
"Ambassador Spanfipple",
"Amelia",
"Amelia (Farming Guild)",
"Ammonite Crab",
"Amrod",
"Amy",
"Ana",
"Anaire",
"Ancestral Glyph",
"Ancient Ghost",
"Ancient monkey",
"Ancient Zygomite",
"Andiess Juip",
"Andras",
"Andrea",
"Andros Mai",
"Aneirin",
"Angel",
"Angelo",
"Anita",
"Anleif",
"Anna",
"Anna Jones",
"Anne Isaakson",
"Annette",
"Anti-Santa",
"Anton",
"Anwen",
"Apothecary",
"Apprentice",
"Apprentice (medium)",
"Apprentice Cordelia",
"Apprentice Felix",
"Apprentice Tamara",
"Apprentice workman",
"Aranwe",
"Arc test",
"Archaeological expert",
"Archaeologist",
"Archeio",
"Archer (Lost City)",
"Archmage Sedridor",
"Archpriest of the Unicorn",
"Arcis",
"Aredhel",
"Aretha",
"Arhein",
"Arianwyn",
"Aristarchus",
"Armod",
"Armour salesman",
"Armourer (tier 1)",
"Armourer (tier 2)",
"Armourer (tier 3)",
"Armourer (tier 4)",
"Armourer (tier 5)",
"Army Commander",
"Arno",
"Arnold Lydspor",
"Arnor",
"Arsen the Thief",
"Art",
"Art Critic Jacques",
"Arthur the Clue Hunter",
"Artimeus",
"Artur Hosidius",
"Arvel",
"Arzinian Being of Bordanzan",
"Ash",
"Ashild",
"Ashuelot Reis",
"Askeladden",
"Asleif Hamalsdotter",
"Assassin",
"Assassin (A Kingdom Divided)",
"Assistant",
"Assistant Brock",
"Assistant Le Smith",
"Assistant Lori",
"Assistant Marrow",
"Assistant Serf",
"Assistant Stan",
"Asteros Arceuus",
"Asyff",
"Atlas",
"Aubury",
"Auctioneer",
"Audmann",
"Auguste",
"Aurel",
"Austri",
"Autumn Elemental",
"Ava",
"Avan",
"Avatar of Creation",
"Avatar of Destruction",
"Awowogei",
"Awowogei (2021 Birthday event)",
"Awusah the Mayor",
"Ayesha",
"Azzanadra",
"Baba Yaga",
"Baby chinchompa",
"Baby impling",
"Baby mole",
"Baby Mole (NPC)",
"Badger",
"Bailey",
"Baker",
"Bakuna",
"Bald Headed Eagle",
"Ball boy",
"Balloon animal",
"Bandit (The Big Heist Lodge)",
"Bandit Leader",
"Bandit shopkeeper",
"Banisoch",
"Bank guard",
"Banker",
"Banker (Al Kharid)",
"Banker (Arceuus)",
"Banker (Canifis)",
"Banker (Darkmeyer)",
"Banker (Dorgesh-Kaan)",
"Banker (Draynor Bank Robbery)",
"Banker (Etceteria)",
"Banker (Farming Guild)",
"Banker (Ferox Enclave)",
"Banker (Hosidius)",
"Banker (Keldagrim)",
"Banker (Lletya)",
"Banker (Lovakengj)",
"Banker (Mos Le'Harmless)",
"Banker (Port Piscarilius)",
"Banker (Prifddinas)",
"Banker (Shayzien)",
"Banker (Shilo Village)",
"Banker (Sophanem)",
"Banker (Tutorial Island)",
"Banker (Varrock)",
"Banker (Ver Sinhaza)",
"Banker (Zanaris)",
"Banker tutor",
"Banknote Exchange Merchant",
"Baraek",
"Barb-tailed kebbit",
"Barbara",
"Barbarian (2021 Halloween event)",
"Barbarian guard",
"Bardur",
"Barfy Bill",
"Barge foreman",
"Barge guard",
"Barge workman",
"Barker",
"Barlak",
"Barmaid",
"Barmaid (historical)",
"Barman (Blurberry Bar)",
"Barman (King's Axe Inn)",
"Barman (Ratpit bar)",
"Barman (unused)",
"Barnabus Hurma",
"Bartak",
"Bartender (2020 Easter event)",
"Bartender (Blue Moon Inn)",
"Bartender (Dancing Donkey Inn)",
"Bartender (Dead Man's Chest)",
"Bartender (Dragon Inn)",
"Bartender (Flying Horse Inn)",
"Bartender (Forester's Arms)",
"Bartender (Jolly Boar Inn)",
"Bartender (Rusty Anchor Inn)",
"Bartender (Sheared Ram)",
"Bartender (The Big Heist Lodge)",
"Bast",
"Bat (Hallowed Sepulchre)",
"Batt Mellamy",
"Battle tortoise display",
"Bear Cub (Prifddinas)",
"Bearded gorilla",
"The Beast",
"Beaver",
"Bedabin Nomad",
"Bedabin Nomad Guard",
"Bedread the bold",
"Bee keeper",
"'Beedy-eye' Jones",
"'Beefy' Burns",
"Bees!",
"Beggar",
"Beigarth",
"Beite",
"Bellemorde",
"Belona",
"Bench (What Lies Below)",
"Benjamin",
"Benny",
"Bentamir",
"Bernald",
"Berry (Woodcutting Guild)",
"Bert",
"Betty",
"'Betty' B.Boppin",
"Beverly",
"Biblia",
"Big Dave",
"Big Dave (2022 Birthday event)",
"Big fish",
"Big Mo",
"BigRedJapan",
"Bill",
"Bill Teach",
"Billam",
"Billy",
"Billy Rehnison",
"Billy, a guard of Falador",
"'Birds-Eye' Jack",
"Bjorn",
"Black Cat",
"Black geist",
"Black Knight Captain",
"Black salamander (Hunter)",
"Black swan",
"Black warlock",
"'Black-eye'",
"Blackjack seller",
"Blaec",
"Blair",
"Blandebir",
"Blanin",
"Blasidar the sculptor",
"Blast Furnace Foreman",
"Blasted ore (NPC)",
"Blitzen",
"Blood tithe (NPC)",
"Bloodhound",
"Blue geist",
"Blue h'ween Mask (2013 Rare Drops)",
"Blue monkey",
"Blue Opal Director",
"Blue Opal Secretary",
"Blue partyhat (2013 April Fools)",
"Blue partyhat (2013 Rare Drops)",
"Blue Sheep",
"Blurberry",
"Boar31337Killer",
"Bob",
"Bob (2021 Birthday event)",
"Bob (cat)",
"Bob (Enlightened Journey)",
"Bob (Mahogany Homes)",
"Bob (Sinclair)",
"Bob Barter (herbs)",
"Bob, another guard of Falador",
"Bobawu",
"Bobbing fossil",
"Bolkoy",
"Bologa",
"Bolongo",
"Bonafido",
"Boneguard",
"Bones (kitten)",
"Bonzara",
"Bonzo",
"Boot",
"Border Guard",
"Bork Sigmundson",
"Boulder",
"Boulder (Mac)",
"Boulder (Viyeldi caves)",
"Bouquet Mac Hyacinth",
"Bow and Arrow salesman",
"Boy",
"Brambickle",
"Brana",
"Branwen",
"Bravek",
"Breive",
"Brendt",
"Brewer",
"Brian",
"Brian (Rimmington)",
"Brian O'Richard",
"Briget",
"Brimstail",
"Broken Handz",
"Brother Aimeri",
"Brother Althric",
"Brother Brace",
"Brother Cedric",
"Brother Jered",
"Brother Jered (2021 Halloween event)",
"Brother Kojo",
"Brother Maledict",
"Brother Omad",
"Brother Tranquility",
"Brown Engine Director",
"Brown Engine Secretary",
"Brownie",
"Brugsen Bursen",
"Brundt the Chieftain",
"Bryn",
"Bugs",
"Bugs (2018 Easter event)",
"Builder",
"Buinn",
"Bunkdo",
"Bunkwicket",
"Bunny ears (2013 Rare Drops)",
"Bunny Man",
"Buoy",
"Burkor",
"Burntmeat",
"Burntof",
"Butler",
"Butler Jarvis",
"Butler Jones",
"Butterfly",
"Butterfly (2019 Halloween event)",
"Butterfly (troll)",
"C0lect0r890",
"C4ssi4n",
"Cabin boy",
"Cabin Boy Colin",
"Cabin Boy Herbert",
"Cabin boy Jenkins",
"Caden Azro",
"Caerbannog",
"Caerwyn",
"Cait",
"Caleb",
"Calin",
"Callisto cub",
"Cam the Camel",
"Camarst",
"Camel",
"Camel display",
"Camorra",
"Candle maker",
"Candle seller",
"Caninelle Draynar",
"Cannoneer",
"Cap'n Hand",
"Cap'n Izzy No-Beard",
"Capt' Arnav",
"Capt' Arnav (2022 Birthday event)",
"Captain",
"Captain Barnaby",
"Captain Bentley",
"Captain Bleemadge",
"Captain Braindeath",
"Captain Bruce",
"Captain Cain",
"Captain Cleive",
"Captain Daerkin",
"Captain Dalbur",
"Captain Donnie",
"Captain Dudi",
"Captain Emmemji",
"Captain Errdo",
"Captain Ginea",
"Captain Janaway",
"Captain Kalt",
"Captain Khaled",
"Captain Klemfoodle",
"Captain Lamdoo",
"Captain Lawgof",
"Captain Magoro",
"Captain Ninto",
"Captain Pudi",
"Captain Rachelle",
"Captain Rimor",
"Captain Rovin",
"Captain Sdiar",
"Captain Shanks",
"Captain Shoracks",
"Captain Siad",
"Captain Tobias",
"Captain Tock",
"Captain Tom",
"Captain Wimto",
"Carado",
"Caranthir",
"Carl",
"Carla",
"Carnivus Belamorta",
"Carol",
"Carol (Christmas 2016)",
"Caroline",
"Carpenter",
"Carpenter Kjallak",
"Cart Camel",
"Cart conductor",
"Cassie",
"Cat",
"Cat (2021 Easter event)",
"Cat (Farming Guild)",
"Cat (Meiyerditch)",
"Cat (Wintertodt Camp)",
"Catalina",
"Cave bug larva",
"Cave goblin (Dorgesh-Kaan)",
"Cave goblin (train station)",
"Cave goblin child",
"Cave goblin worker",
"Cave monk",
"Cave snake",
"Cavemouth",
"Cavey Davey",
"Cecilia",
"Cecilia (2021 Christmas event)",
"Celebrian",
"Celegorm",
"Celyn",
"Centaur",
"Ceril Carnillean",
"Cerulean twitch",
"Ceto",
"Chadwell",
"Chaeldar",
"Chair (The Slug Menace)",
"Chamber guardian",
"Chancy",
"Charles",
"Charles (Fossil Island)",
"Charles Charlington",
"Charley",
"Charlie",
"Charlie (prisoner)",
"Charlie Brown",
"Charlie the cook",
"Charlie the Tramp",
"Charmed Warrior",
"Checkal",
"Cheerleader",
"Cheerleader (20th Anniversary event)",
"Chef",
"Chef Olivia",
"Chemist",
"Cheryl",
"Chicken suit (2013 Rare Drops)",
"Chief Farmer",
"Chief servant",
"Chief Tess",
"Child",
"Child (2005 Halloween event)",
"Child (Meiyerditch)",
"Child (Slepe)",
"Chocco",
"Chocolate bunny",
"Chocolate Chicken",
"Chocolate chicken (2015 Easter event)",
"Chocolate demon",
"Chocolate duck",
"Chocolate snakeling",
"Chocolate spider",
"Chompy bird",
"Chompy chick",
"Christmas cracker (2013 Rare Drops)",
"Christopher",
"Chuck",
"Chuck (20th Anniversary event)",
"Cirdan",
"Citizen",
"Civilian",
"Clan Guard",
"Claude",
"Claus the chef",
"Clay golem",
"Cleaner",
"Cleddyf",
"Clerk",
"Clerk (Clan Hub)",
"Clerk (Hosidius)",
"Clerris",
"Clothears",
"Co-ordinator",
"Coal (Blast Furnace)",
"Cob",
"Cocktail seller",
"Coenus",
"Col. O'Niall",
"Colonel Grimsson",
"Combat dummy",
"Combat Test",
"Comet",
"Commander (2013 Goblin Invasion)",
"Commander Connad",
"Commander Fullore",
"Commander Montai",
"Commander Veldaban",
"Commissioner Anwar",
"Common kebbit",
"Competition Judge",
"Conrad King",
"Conwenna",
"Cook (2022 Birthday event)",
"Cook (Blue Moon Inn)",
"Cook (Jolly Boar Inn)",
"Cook (Lumbridge)",
"Cook (servant)",
"Cooking tutor",
"Cool Mom227",
"Copper longtail",
"Copper ore (Blast Furnace)",
"Corkat quo Sihar",
"Cormac",
"Cormorant",
"Cornelius",
"Corpse",
"Corrupted scavenger",
"Cosmic Being",
"Council workman",
"Councillor Andrews",
"Councillor Halgrive",
"Councillor Orson",
"Councillor Unkar",
"Count Check",
"Court judge",
"Cow (2018 Christmas event)",
"Cow31337Killer",
"Cowardly Bandit",
"Cowboy",
"Crab (Beach)",
"Crab (Mos Le'Harmless)",
"Crab (Prifddinas)",
"Cracked Jenny's Tea Cup",
"Crafting tutor",
"Crate (Gertrude's Cat)",
"Crate goblin",
"Crawling hand (mounted)",
"Creakyknees",
"Crefydd",
"Crimson swift",
"Crimsonette van Marr",
"Crone",
"Crow",
"Crunchy",
"Crusher (Penguin Agility Course)",
"Crust of ice",
"Crystal impling",
"Crystal Whirlwind",
"Cupid",
"Curator Haig Halen",
"Curly",
"Curpile Fyod",
"'Currency' The Alchemist",
"Curufin",
"Customer",
"Customer (Dwarf)",
"Customs officer",
"Cute creature",
"Cyreg Paddlehorn",
"Cyrisus",
"D3ad1i F15her",
"Da Vinci",
"Daer Krand",
"Daero",
"Daga",
"Dakh'thoulan Aegis",
"Dalal",
"Dalcian Fang (easy)",
"Dalila",
"Dallas Jones",
"Dalldav",
"Damien Leucurte",
"Dampe",
"Damwin",
"Dancer",
"Dantaera",
"Darcor quo Narga",
"Dark kebbit",
"Dark Mage",
"Dark Mage (Abyss)",
"Dark wizard (Great Kourend)",
"Darkmeyer Slave",
"Darkmeyer Slave (non-interactive)",
"Darren",
"Darren (Piscarilius)",
"Dartog",
"Darve",
"Daryl",
"Dasher",
"Dashing kebbit",
"Dave",
"Davey",
"David",
"David (Fossil Island)",
"David (Varrock Museum)",
"Davon",
"Dead Monk",
"Death (Halloween)",
"Death (NPC)",
"Debra",
"Del-Monty",
"Delrith",
"Demon butler",
"Denadu",
"Denath",
"Denulth",
"Derni",
"Dernu",
"Derrik",
"Derse Venator",
"Derwen (elf)",
"Desert devil",
"Desert eagle",
"Desert Phoenix",
"Desert Spirit",
"Desmodus Lasiurus",
"Despoina Callidra",
"Devan Rutter",
"Devin Mendelberg",
"Dhalak",
"Diana",
"Diango",
"Dig Site workman",
"Digsite workman",
"Dimintheis",
"Diol",
"Dipflip",
"Diphylla Bechstein",
"Disciple of Yama",
"Disk of Returning (2013 Rare Drops)",
"Dobwinkle",
"Dock worker",
"Dockmaster",
"Doctor Orbon",
"Dodgy geezer",
"Dodgy Squire",
"Doe",
"Dog",
"Dog (Museum Camp)",
"Dog (Myths' Guild)",
"Doll (The Corsair Curse)",
"Dolph",
"Dominic Onion",
"Dommik",
"Don",
"Don't Know What",
"Donal",
"Dondakan the Dwarf",
"Donie",
"Donie (2021 Birthday event)",
"Donnacha",
"Donovan the Family Handyman",
"Doomsayer",
"Door man",
"Door-support",
"Doric",
"Doris",
"Doug Deeping",
"Doyen",
"Dr Fenkenstrain",
"Dr Ford",
"Dr Harlow",
"Dr Jekyll",
"Draconis Sanguine",
"Dragon display",
"Dragon impling",
"Dragonkin (A Tail of Two Cats)",
"Dragonkin (Dragon Slayer II)",
"Drain Pipe",
"Drake (2021 Christmas event)",
"Drake (bird)",
"Drasdan Ranor",
"Draul Leptoc",
"Dreven",
"Drew",
"Drezel",
"Driftwood",
"Drill Sergeant",
"Droalak",
"Drogo dwarf",
"Dromund",
"Dromund's cat",
"Dron",
"Drunken Ali",
"Drunken Dwarf",
"Drunken Dwarf (Keldagrim)",
"Drunken Dwarf's Leg",
"Drunken soldier",
"Dryad (unused)",
"Duck (2021 Christmas event)",
"Duck (Common)",
"Duck (Kourend Woodland)",
"Duck (Soul Wars)",
"Ducklings",
"Dugopul",
"Duke",
"Duke Horacio",
"Duke Horacio (2021 Birthday event)",
"Duke Rabbacio",
"Dumpy",
"Dunce",
"Dung",
"Dunstan",
"Duradel",
"Durgok",
"Dusty Aliv",
"Dusuri",
"Dwarf (Death to the Dorgeshuun)",
"Dwarf (Dwarven shopping store)",
"Dwarf (Mining Guild)",
"Dwarf (Motherlode Mine)",
"Dwarf (train station)",
"Dwarven Boatman",
"Dwarven Boatman (ore hauler)",
"Dwarven Engineer",
"Dwarven Ferryman",
"Dwarven Miner",
"Dylan",
"Eadgar",
"Eagle",
"Eagle (giant)",
"'Eagle-eye' Shultz",
"Earth impling",
"Earwen",
"Easter Bunny",
"Easter Bunny (historical)",
"Easter Duck",
"Easter egg (2013 April Fools)",
"Easter egg (2013 Rare Drops)",
"Easter egg bird",
"Easter ring (2013 Rare Drops)",
"Eblis",
"Eclectic impling",
"Ed",
"Ed Wood",
"Edmond",
"Edmond (merchant)",
"Edrahil",
"Edward",
"Eebel",
"Eek",
"Efa",
"Effigy",
"Eg",
"Egg (2019 Easter event)",
"Eggy",
"Eira",
"Ek'ans Chan",
"Ektheme",
"Eldalote",
"Elder Chaos druid (NPC)",
"Elder Gnome child",
"Elder Guard",
"Eldgrim",
"Elemental rock",
"Elena",
"Elena Hosidius",
"Elenwe",
"Elf Tracker",
"Elf warrior (Arandar)",
"Elfinlocks",
"Elgan",
"Elijah",
"Elisabeta",
"Elise",
"Elissa",
"Elite Void Knight",
"Elizabeth",
"Elizabeth (Piscarilius)",
"Elkoy",
"Elladan",
"Ellen",
"Ellena",
"Ellie",
"Ellis",
"Elly the Camel",
"Elnock Inquisitor",
"Elsie",
"Elstan",
"Eluned",
"Eluned (2021 Birthday event)",
"Elven city guard",
"Elven Scout",
"Embalmer",
"Emblem Trader",
"Emem Sharma",
"Emerald Benedict",
"Emilia",
"Emily",
"Enakhra",
"Enchanted Broom",
"Enchanted Bucket",
"Enchantment Guardian",
"Enel",
"Enelye",
"Enerdhil",
"Energy focus",
"Engineer",
"Engineering assistant",
"Enilly",
"Eniola",
"Enoch",
"Enormous Tentacle (Fishing Trawler)",
"Ent",
"Ent (random event)",
"Entomologist",
"Entrance Guardian",
"Eodan",
"Eohric",
"Eoin",
"Epic mager34",
"Episcula Helsing",
"Erdan",
"Erestor",
"Eric",
"Eric (2018 Halloween event)",
"Eric (Jatizso)",
"Erin",
"Ermin",
"Ernest",
"Erodoeht",
"Escaping slave",
"Essence impling",
"Essyllt",
"Estate agent",
"Estate agent (2021 Halloween event)",
"Esther",
"Ethereal Expert",
"Ethereal Fluke",
"Ethereal Guide",
"Ethereal Lady",
"Ethereal Man",
"Ethereal Mimic",
"Ethereal Numerator",
"Ethereal Perceptive",
"Eudav",
"Eve",
"Eve (2020 Halloween event)",
"Evil Bob",
"Evil creature",
"Evil Dave",
"Ewesey",
"Examiner",
"Executioner",
"Eye (Abyssal Nexus)",
"Ezekial Lovecraft",
"Factory Manager",
"Factory Worker",
"Fadli",
"Fairy",
"Fairy (Fairy Resistance Hideout)",
"Fairy (Zanaris market)",
"Fairy Aeryka",
"Fairy chef",
"Fairy Fixit",
"Fairy Godfather",
"Fairy Nuff",
"Fairy Queen",
"Fairy shop assistant",
"Fairy shop keeper",
"Fairy Very Wise",
"Fake man",
"Falador Knight",
"Falo the Bard",
"Fancy Dan",
"Fanellaman",
"Farid Morrisane (ores and bars)",
"Farmer (Hosidius)",
"Farmer (Miscellania)",
"Farmer (The Golden Field)",
"Farmer Brumty",
"Farmer Fromund",
"Farmer Gricoller",
"Farmer Hayfield",
"Farmer Maggot",
"Farolt",
"Fat Rocco",
"Fat Tony",
"Father Aereck",
"Father Aereck (2021 Birthday event)",
"Father Badden",
"Father Buckerek",
"Father Eysseric",
"Father Jean",
"Father Lawrence",
"Father Reen",
"Father Urhney",
"Fayeth",
"Feanor",
"Feldip weasel",
"Felfiz Yaryus",
"Felkrash",
"Female amur leopard",
"Female lion",
"Female slave",
"Female snow leopard",
"Female tiger",
"Femi",
"Feral Vampyre (NPC)",
"Ferd",
"Fernahei",
"Ferox",
"Ferret (Hunter)",
"Ferryman Nathwood",
"Ferryman Sathwood",
"Ffoni",
"Fidelio",
"Fightslave",
"Filamina",
"Filliman Tarlock",
"Financial Advisor",
"Financial Seer",
"Financial Wizard",
"Finarfin",
"Findis",
"Finduilas",
"Fingolfin",
"Fingon",
"Finn",
"Fionella",
"Fionn",
"Fior",
"Fire Wave (Judge of Yama)",
"First mate 'Davey-boy'",
"First Mate Deri",
"First Mate Peri",
"Fish (angelfish)",
"Fish (black moor fantail)",
"Fish (discus)",
"Fish (harlequin)",
"Fish (neon tetra)",
"Fish (paradise)",
"Fish (pearl danio)",
"Fish (red fantail)",
"Fish monger",
"Fish monger (The Warrens)",
"Fish shoal",
"Fishbowl (pet)",
"Fisherman (Fishing Platform)",
"Fisherman (Holy Grail)",
"Fisherman (Port Piscarilius)",
"Fisherman (Rellekka)",
"Fisherman Frodi",
"Fishing spot (2022 Birthday event)",
"Fishing spot (aerial fishing)",
"Fishing spot (barbarian)",
"Fishing spot (big net, harpoon)",
"Fishing spot (Braindeath Island)",
"Fishing spot (cage, harpoon)",
"Fishing spot (Camdozaal)",
"Fishing spot (dark crab)",
"Fishing spot (Enchanted Valley)",
"Fishing spot (frogspawn)",
"Fishing spot (Hemenster)",
"Fishing spot (karambwan)",
"Fishing spot (karambwanji)",
"Fishing spot (lava eel)",
"Fishing spot (minnow)",
"Fishing spot (Piscatoris Fishing Colony)",
"Fishing spot (sacred eel)",
"Fishing spot (small net, bait)",
"Fishing spot (swamp)",
"Fishing spot (Tempoross Cove)",
"Fishing spot (Tutorial Island)",
"Fishing tutor",
"Fishmonger",
"Fishrunner82",
"Flax keeper",
"Flaygian Screwte",
"Flies",
"Flippa",
"Floki",
"Florin",
"Flosi Dalksson",
"Flower",
"Flower Girl",
"Fly trap",
"Flying Book",
"Flying papers",
"Flynn",
"Forester (hard)",
"Forester (NPC)",
"Former Vampyre",
"Fornek quo Maten",
"Fortunato",
"Fossegrimen",
"Fossil Collector",
"Francis",
"Francois",
"Frank",
"Frank (Bloodveld)",
"Frankie",
"Franklin Caranos",
"Freaky Forester",
"Freald",
"Fred the Farmer",
"Freja",
"Fremennik Warrior",
"Frenita",
"Freygerd",
"Freygerd (Jatizso)",
"Fridgeir",
"Fridleif Shieldson",
"Frincos",
"Fritz the Glassblower",
"Frizzy Skernip",
"Frog (Kiss the frog)",
"Frog (Make-over mage)",
"Frog (Mount Quidamortem)",
"Frog (Ruins of Camdozaal)",
"Frog (Zanaris)",
"Frog prince",
"Frog princess",
"Froono",
"Frosty snakeling",
"Frosty spider",
"Fuggy",
"Fullangr",
"Fur trader (East Ardougne)",
"Fur trader (Rellekka)",
"Furnace grate",
"Fycie",
"Fyiona Fray (easy)",
"G.L.O. Caranock",
"Gabe",
"Gabooty",
"Gabriela",
"Gadrin",
"Gaius",
"Galahad",
"Galana",
"Galathil",
"Gallow",
"Gamer",
"Gamfred",
"Garai",
"Garbek quo Maten",
"Garden supplier",
"Gardener (unused)",
"Gardener Ghost",
"Gardener Gunnhild",
"Gardener Jay Jr.",
"Gargh",
"Garkor",
"Garl",
"Garth",
"Garth (Theatre of Blood)",
"Garv",
"Gate of War",
"Gatekeeper",
"Gauss",
"Gee",
"Gelin",
"Gelmir",
"Gem (Clan Hall)",
"Gem merchant",
"Gem merchant (Kourend Castle)",
"Gem trader",
"Gene",
"General Babacus",
"General Bentnoze",
"General Hining",
"General Khazard",
"General Kilian",
"General Salara",
"General Vir",
"General Wartface",
"Generic Diplomat",
"Genie",
"Genie (Spirits of the Elid)",
"George Laxmeister",
"Georgie",
"Gerald",
"Gerrant",
"Gertrude",
"Gertrude's cat (NPC)",
"Gethin",
"Ghaslor the Elder",
"Ghast",
"Ghommal",
"Ghost (Hopespear)",
"Ghost (Malignius Mortifer)",
"Ghost (Mynydd)",
"Ghost (Ruins of Camdozaal)",
"Ghost (Soul Wars)",
"Ghost (The General's Shadow)",
"Ghost banker",
"Ghost captain",
"Ghost captain (ghostship)",
"Ghost disciple",
"Ghost farmer",
"Ghost guard",
"Ghost innkeeper",
"Ghost sailor",
"Ghost shopkeeper",
"Ghost villager",
"Ghostly figure",
"Ghostly thrall (beta)",
"Gianne jnr.",
"Giant (Surprise Exam)",
"Giant lobster",
"Giant squirrel",
"Gielinor Guide",
"Gilbert",
"Giles",
"Gileth",
"Gillie Groats",
"Giral bat",
"Gita Prymes",
"Gladiator",
"Glenda",
"Glorfindel",
"Glough",
"Glouphrie the Untrusted",
"Gnocci the Cook",
"Gnome (2013 Thanksgiving event)",
"Gnome (A Tail of Two Cats)",
"Gnome (Grim Tales)",
"Gnome (Mourner Headquarters)",
"Gnome ball referee",
"Gnome baller",
"Gnome banker",
"Gnome child (2013 Thanksgiving event)",
"Gnome child (2018 Birthday event)",
"Gnome Child (20th Anniversary event)",
"Gnome Coach",
"Gnome emissary",
"Gnome pilot (historical)",
"Gnome shop keeper",
"Gnome trainer",
"Gnome traveller",
"Gnome Waiter",
"Gnome winger",
"Gnormadium Avlafrim",
"Gnosi",
"Goat Poo",
"Goblin (2014 Goblin Invasion)",
"Goblin (2014 Goblin Invasion, spy)",
"Goblin (2019 Halloween event)",
"Goblin (2020 Christmas event)",
"Goblin (Surprise Exam)",
"Goblin Cook",
"Goblin fish",
"Goblin guard",
"Goblin guard (Land of the Goblins)",
"Goblin priest",
"Goblin Recruiter",
"Goblin scribe",
"Godric",
"Gold ore (Blast Furnace)",
"Golden sheep",
"Golden warbler",
"Goldie",
"Golova",
"Golrie",
"Gordon",
"Goreu",
"Gorhak quo Narga",
"Gorilla (NPC)",
"Gossip",
"Gourmet",
"Gourmet impling",
"GPDT employee",
"Grace",
"Grail Maiden",
"Grand Exchange Clerk",
"Grandpa Jack",
"Grasslegs",
"Grave",
"Grave digger",
"Graveyard Guardian",
"Gravingas",
"Greasycheeks",
"Greater ghostly thrall",
"Greater skeletal thrall",
"Greater zombified thrall",
"Green fireflies",
"Green geist",
"Green Gemstone Director",
"Green Gemstone Secretary",
"Green h'ween Mask (2013 Rare Drops)",
"Green partyhat (2013 April Fools)",
"Green partyhat (2013 Rare Drops)",
"Green Sheep",
"Greengrocer",
"Gregg",
"Greldo",
"Grew",
"Grigor Rasputin",
"Grigore",
"Grimesquit",
"Grimgnash",
"Grinka Krast",
"Grish",
"Group Iron tutor",
"Group Storage tutor",
"Grubfoot",
"Grubor",
"Gruff McScruff",
"Grug",
"Gruh",
"Grum",
"Grundt",
"Grunsh",
"Gruva Patrull",
"Guanic bat",
"Guard (2014 Goblin Invasion)",
"Guard (2014 Goblin Invasion, spy)",
"Guard (2020 Easter event)",
"Guard (Carnillean)",
"Guard (Combat Training Camp)",
"Guard (Courthouse)",
"Guard (East Varrock)",
"Guard (Etceteria)",
"Guard (Goblin)",
"Guard (Goutweed)",
"Guard (Jatizso)",
"Guard (King's Ransom)",
"Guard (Miscellania Castle)",
"Guard (Miscellania)",
"Guard (Mountain Camp)",
"Guard (Port Sarim)",
"Guard (Port Sarim, sleeping)",
"Guard (Ratcatchers)",
"Guard (Sinclair Mansion)",
"Guard Captain",
"Guard Recruiter",
"Guard Vemmeldo",
"Guardian mummy",
"Gublinch",
"Guidor",
"Guildmaster",
"Guildmaster Jane",
"Guildmaster Lars",
"Guilin",
"Guinevere",
"Gujuo",
"Gull",
"Gulldamar",
"Gulluck",
"'Gummy'",
"Gundai",
"Gundik",
"Gunnar Holdstrom",
"Gunnjorn",
"Gunslik",
"Gurl",
"Gwallter",
"Gwerin Hapus",
"Gwindor",
"Gwyl",
"Gwyn",
"Gypsy Aris",
"Gyr falcon",
"H.A.M. Deacon",
"H.A.M. Member",
"Habibah",
"Hadley",
"Haemas Lamescus",
"Haera",
"Hafuba",
"Hairdresser",
"Hairdresser (2021 Christmas event)",
"Hajedy",
"Haldor quo Keran",
"Half full wine jug (2013 Rare Drops)",
"Half-soulless",
"Half-Zombie",
"Halla",
"Hallak",
"HAM member (Death to the Dorgeshuun)",
"Hamab",
"Hamal the Chieftain",
"Hameln the Jester",
"Hamid",
"Haming",
"Hammerspike Stoutbeard",
"Hanchen the Hound",
"Hand in a box",
"Hans",
"Hans (2022 Birthday event)",
"Happy child",
"Happy gnome child",
"Hari",
"Haris",
"Harold",
"Harold Evans",
"Harpert",
"Harrallak Menarous",
"Harry",
"Haskell",
"Hassan",
"Hassan (2022 Birthday event)",
"Hatius Cosaintus",
"Hats & scarves (2013 Rare Drops)",
"Haze",
"Hazeel",
"Hazelmere",
"Head chef",
"Head Mourner",
"Head mourner (removed)",
"Heckel Funch",
"Hegir",
"Helemos",
"Helena",
"Helga",
"Hell-Rat",
"Hell-Rat Behemoth",
"Hellcat",
"Hellpuppy",
"Helpline Assistant",
"Hendor",
"Hendor (elf)",
"Hengrad",
"Henja",
"Henryeta Carnillean",
"Herbi",
"Herbiboar",
"Herman Caranos",
"Heron",
"Herquin",
"Herquin (2021 Christmas event)",
"Hervi",
"Heskel",
"Hetty",
"Hewey",
"Hickton",
"Hieve",
"High Priest (2013 Goblin Invasion)",
"High Priest (Entrana)",
"High Priest (Sophanem)",
"High Priest Bighead",
"High Priest of Scabaras",
"High Priestess Zul-Harcinqa",
"Hild",
"Hild (Miscellania)",
"Hirko",
"Historian Duffy",
"Historian Minas",
"Hiylik Myna",
"Hobbes",
"Hofuthand (weapons and armour)",
"Hogst",
"Holgart",
"Holly",
"Holoy",
"Homunculus",
"Honest Jimmy",
"Honour guard",
"Hooded Figure",
"Hooded Stranger",
"Hooknosed Jack",
"Hoop Snake",
"Hopleez",
"Hops (Biohazard)",
"Horace",
"Horacio",
"Horned graahk",
"Horphis",
"Horvik",
"Hosa",
"Hotpheex",
"House (Berty)",
"HRH Hrafn",
"Hring Hring",
"Hudo",
"Hudon",
"Hugor",
"Humroc",
"Hunding",
"Hunting expert",
"Hunting expert (Red chinchompa hunting ground)",
"Hunting expert (Rellekka Hunter area)",
"Hura",
"Iago",
"Ian",
"Ian (Prifddinas)",
"Ice block",
"Ice troll (Desert Treasure)",
"Icelord (2019 Christmas event)",
"Icicle",
"Idril",
"Idris",
"Ifaba",
"Iffie",
"Iffie (2021 Halloween event)",
"Ignatius Vulcan",
"Ignisia",
"Ikkle hydra",
"Ileana",
"Ilfeen",
"Ima",
"Imerominia",
"Imiago",
"Imin",
"Iminye",
"Immenizz",
"Imp (Castle Wars)",
"Imp defender",
"Indis",
"Information clerk",
"Inga",
"Ingrid",
"Ingrid Hradson",
"Ingwe",
"Ingwion",
"Inn Keeper",
"Innocent-looking key",
"Intruder",
"Iona",
"Irena",
"Irene",
"Irksol",
"Iron Man tutor",
"Iron ore (Blast Furnace)",
"Irwin Feaselbaum",
"Ish the Navigator",
"Ishmael",
"Islwyn",
"Istoria",
"Ithoi the Navigator",
"Ivan",
"Ivan Strom",
"Ivy",
"Iwan",
"Iwazaru",
"Jabari",
"Jack",
"Jack (Christmas 2013)",
"Jack Frost",
"Jack lantern mask (2013 Rare Drops)",
"Jack Sails",
"Jack Seagull",
"Jacky Jester",
"Jade (Warriors' Guild)",
"Jadid",
"Jagbakoba",
"Jal-nib-rek",
"James",
"Jamila",
"Jaraah",
"Jardric",
"Jari",
"Jarr",
"Jarvald",
"Jarvis",
"Jatix",
"Jayene Kliyn (medium)",
"Jeb",
"Jeed",
"Jeff (child)",
"Jeff (Mahogany Homes)",
"Jelly (mountain troll)",
"Jennifer",
"Jennifer (Shayzien)",
"Jenny Blade",
"Jeremy Clerksin",
"Jerico",
"Jess",
"Jess (2019 Christmas event)",
"Jessie",
"Jethick",
"Jewelled Crab",
"Jex",
"Jig cart",
"Jill",
"Jiminua",
"Jimmy (Warriors' Guild)",
"Jimmy Dazzler",
"Jimmy the Chisel",
"Joe",
"Joe (Fight Arena)",
"Joe (jail)",
"Jofridr Mordstatter",
"Johanhus Ulsbrecht",
"John",
"John (Fossil Island)",
"Johnathon",
"Jokul",
"Jon",
"Jonas",
"Jonathan",
"Jorra",
"Jorral",
"Jorzik",
"Joshua",
"Jossik",
"Juan",
"Jubbly bird",
"Jukat",
"Julie",
"Juliet",
"Jumaane",
"Juna",
"Jungle eagle",
"Jungle forester",
"Junior Navigator",
"Jury",
"Justin Servil",
"Justine",
"Jyn",
"K'klik",
"Kaal-Ket-Jor",
"Kaal-Mej-San",
"Kaal-Xil-Dar",
"Kael Forshaw",
"Kaht B'alam",
"Kai",
"Kaleb Paramaya",
"Kalphite Larva",
"Kalphite princess",
"Kalron",
"Kamen",
"Kamfreena",
"Kanel",
"Kangai Mau",
"Kaqemeex",
"Karaday",
"Karam",
"Karamthulhu (unused NPC)",
"Kardia",
"Karim",
"Karl",
"Kaston",
"Kathy Corkat",
"Katrine",
"Kaylee",
"Kazemde",
"Kazgar",
"Kbd head (mounted)",
"Keepa Kettilon",
"Keith",
"Kelvin",
"Kelyn",
"Kendall",
"Kenelme",
"Kennith",
"Kent",
"Ket'sal K'uk",
"Key Master",
"KGP Agent",
"KGP Guard",
"Kharid Scorpion",
"Kharrim",
"Khazard barman",
"Khorvak, a dwarven engineer",
"Kikazaru",
"Killer",
"Kilron",
"Kineer",
"King Arthur",
"King Bolren",
"King Gjuki Sorvott IV",
"King Healthorg",
"King Lathas",
"King Narnode Shareen",
"King rat",
"King Roald",
"King Snagwort",
"King Thoros",
"King Vargas",
"King's Messenger",
"Kitten",
"Kitten (Gertrude's Cat)",
"Kjedelig Uppsen",
"Kjut",
"Klank",
"Klarense",
"Klenter",
"Knight (Enakhra's Lament)",
"Knight (Falador Party Room)",
"Knight (Sir Gerry)",
"Knight of the Lion",
"Knight of the Owl",
"Knight of the Unicorn",
"Knight of the Wolf",
"Knight of Varlamore",
"Koanee",
"Koftik",
"Konar quo Maten",
"Konoo",
"Kormar quo Maten",
"Kortan",
"Koschei the deathless",
"Kragen",
"Krato",
"Kroy",
"Kryket bat",
"Krystilia",
"Kualti",
"Kupus Varza",
"Kurt",
"Kylie Minnow",
"Lacey",
"Lady Carys Hefin",
"Lady Crombwick",
"Lady Ffion Meilyr",
"Lady Keli",
"Lady Nadezhda Shadum",
"Lady Servil",
"Lady Shauna Piscarilius",
"Lady Table",
"Lady Tangwen Trahaearn",
"Lady Vulcana Lovakengj",
"Lahsram",
"Lalli",
"Lamb",
"Lammy Langle",
"Lan the Butcher",
"Lanthus",
"Large zombie monkey",
"Larran",
"Larrissa",
"Larry",
"Larry (2021 Christmas event)",
"Larry (Enlightened Journey)",
"Larry (Mahogany Homes)",
"Larry (merchant)",
"Larry Leprechaun (2022 Birthday event)",
"Larxus",
"Lasenna Rasputin",
"Latlink Fastbell",
"Launa",
"Lauretta",
"Layleen",
"Lazim",
"Lazy cat",
"Le-sabrè",
"Lead Navigator",
"League Tutor (Shattered Relics League)",
"Leagues Assistant",
"Leagues Assistant (Shattered Relics League)",
"Leagues Tutor",
"Leatherworker",
"'Lecherous' Lee",
"Lector Gura",
"Leech display",
"Leela",
"Leela (Mahogany Homes)",
"Leenz",
"Legends guard",
"Leke quo Keran",
"Lennissa",
"Lenny",
"Lensa (Jatizso)",
"Lenwe",
"Lenyig Karna",
"Leo",
"Leon",
"Lesser Fanatic",
"Lesser ghostly thrall",
"Lesser skeletal thrall",
"Lesser zombified thrall",
"Li'l lamb",
"Liam",
"Librarian",
"Lidio",
"Lieutenant Schepbur",
"Lieve McCracken",
"Light creature",
"Lightning cloud",
"Lil' creator",
"Lil' zik",
"Lilifang",
"Liliwen",
"Lillia",
"Lilly",
"Lindir",
"Lisa",
"Lisse Isaakson",
"Litara",
"Lithil",
"Little Mo",
"Little nightmare",
"Lizard (Quidamortem)",
"Lizard display",
"Lizard man (2014 April Fools)",
"Lizard man (2014 Birthday event)",
"Lleidr Golau",
"Lliann",
"Llio",
"Loading crane",
"Lobby Cow",
"Local",
"Local Gnome",
"Lofu",
"Logava",
"Logios",
"Logosia",
"Loinur",
"Lokar Searunner",
"Loki",
"Lokraa quo Sihar",
"Lollk",
"Longbow Ben",
"Longhall Bouncer",
"Look-out",
"Looming shadow",
"Lord Alexei Jovkai",
"Lord Baxtorian Cadarn",
"Lord Crombwick",
"Lord Daquarius",
"Lord Iban",
"Lord Iestin Iorwerth",
"Lord Ieuan Amlodd",
"Lord Iorwerth",
"Lord Kandur Hosidius",
"Lord Marshal Brogan",
"Lord Mischa Myrmel",
"Lord Piquan Crwys",
"Lord Rologarth",
"Lord Shiro Shayzien",
"Lord Trobin Arceuus",
"Lorelai",
"Lornor quo Narga",
"Lorraine",
"Louie Legs",
"Louisa",
"Lovada",
"Lovakengj Engineer",
"Love Cats",
"Lowe",
"Lowerniel Drakan",
"Lubufu",
"Lucien",
"Lucky impling",
"Lucy",
"Lumberjack Leif",
"Lumbridge Cow",
"Lumbridge Guide",
"Lumbridge Sheep",
"Lumdo",
"Lumiere",
"Luminata",
"Lumo",
"Luna",
"Lundail",
"Lunderwin",
"Lurgon",
"Luscion",
"Luthas",
"Lutist",
"Lutwidge",
"Lux grub",
"Lyra",
"Mac",
"Macaroni Penguin",
"Mad melvin96",
"Mad skavid",
"Madame Caldarium",
"Maedhros",
"Maeglin",
"Mage (easy)",
"Mage of Zamorak",
"Mage of Zamorak (Ourania)",
"Magic combat tutor",
"Magic Instructor",
"Magnus Gram",
"Magpie impling",
"Mahtan",
"Maid",
"Mairin",
"Maisa",
"Major Attack",
"Major Collect",
"Major Defend",
"Major Heal",
"Makeover Mage",
"Malak",
"Male amur leopard",
"Male lion",
"Male slave",
"Male snow leopard",
"Male tiger",
"Malignius Mortifer",
"Mallak quo Keran",
"Mama",
"Mamma Bufetta",
"Man (Canifis bridge)",
"Man (Catacombs of Kourend)",
"Man (Hosidius)",
"Man (West Ardougne)",
"Mandrith",
"Mandy",
"Maniacal monkey (Hunter)",
"Manni the Reveller",
"Marfet",
"Maria Gadderanks",
"Maria Gunnars",
"Mariah",
"Marionette set (2013 Rare Drops)",
"Marisi",
"Marius",
"Marius Giste",
"Mark",
"Mark (dog)",
"Market seller",
"Markog",
"Marley",
"Marlo",
"Marmor quo Narga",
"Marten",
"Martha Rehnison",
"Martin Holt",
"Martin the Master Gardener",
"Martin Thwait",
"Martina Scorsby",
"Marwolaeth Dawnsio",
"Mary",
"Mary (2019 Christmas event)",
"Mary (Getting Ahead)",
"Masked stranger",
"Master Chef",
"Master Crafter",
"Master Farmer",
"Master fisher",
"Master Navigator",
"Master smithing tutor",
"Matilda",
"Matthew",
"Matthias",
"Mattimeo",
"Mawnis Burowgar",
"Mawrth",
"Mayor Hobb",
"Maz",
"Mazchna",
"Maze Guardian",
"Mazion",
"Meddwl Ymlaen Llaw",
"Medium catalytic guardian",
"Medium elemental guardian",
"Medium ninja monkey",
"Meegle",
"Megan",
"Mehhar",
"Meiyerditch citizen",
"Meiyerditch miner",
"Mekritus A'hara",
"Melana Moonlander",
"Melee combat tutor",
"Meleti",
"Melina",
"Melvin",
"Memory of Seren",
"Menaphite Guard",
"Menaphite Leader",
"Mercenary (Ferox Enclave)",
"Mercenary (Theatre of Blood)",
"Mercy",
"Meredith",
"Merlin",
"Mernia",
"Mernik",
"Meskhenet",
"Messenger",
"Metarialus",
"Meteora",
"Mi-Gor",
"Mia",
"Miala",
"Miazrqa",
"Mibbiwocket",
"Mihail",
"Mike",
"Miles",
"Milkee",
"Milli Rehnison",
"Millie Miller",
"Miltog",
"Mime",
"Mimm",
"Mine cart driver",
"Mine supervisor",
"Miner (Jatizso)",
"Miner (Motherlode Mine)",
"Miner Magnus",
"Miniature chaotic clouds",
"Mining Instructor",
"Mining tutor",
"Miodvetnir",
"Miriam",
"Miriel",
"Mischievous ghost",
"Misdrievus Shadum",
"Mishkal'un Dorn",
"Miss Cheevers",
"Miss Schism",
"Mist",
"Mistag",
"Mithrellas",
"Mithril ore (Blast Furnace)",
"Mittens",
"Mizaru",
"Moe",
"Mofina",
"Mofina (2021 Birthday event)",
"Moggy",
"Mogre Guard",
"Mogrim",
"Moldof",
"Mole display",
"Molly",
"Monk (2021 Halloween event)",
"Monk (Devious Minds)",
"Monk (Entrana)",
"Monk (Harmony Island)",
"Monk (Lost City)",
"Monk of Entrana",
"Monkey (magic carpet)",
"Monkey (Monkey Madness I)",
"Monkey (Trouble Brewing)",
"Monkey Archer (teaser)",
"Monkey boy",
"Monkey Child",
"Monkey display",
"Monkey minder",
"Monkey on cow",
"Monkey on unicorn",
"Mord Gunnars",
"Mordan Nikazsi",
"Morgan",
"Morgan Le Faye",
"Mori",
"Morris",
"Mort Nightshade",
"Mort'ton local",
"Morten Holdstrom",
"Mortina Daubenton",
"Morvran",
"Mosol Rei",
"Most of a Zombie",
"Mother",
"Mother Mallum",
"Moths",
"Mountain Dwarf",
"Mountain Dwarf (historical)",
"Mountain goat",
"Mountain Goat (Mountain Camp)",
"Mountain Guide",
"Mounted terrorchick gnome",
"Mourner (Biohazard)",
"Mourner (Mourner Tunnels)",
"Mourner (Plague City)",
"Mouse (Witch's House)",
"Movario",
"Mr. Mordaut",
"Ms. Hynn Terprett",
"Mubariz",
"Mummy (Surprise Exam)",
"Muncher",
"Munty",
"Murcaily",
"Murfet",
"Murky Matt (runes)",
"Murky Pat",
"Murng bat",
"Murphy",
"Muruwoi",
"Museum guard",
"Mushroom (mountain troll)",
"My Arm",
"My Arm (2022 Birthday event)",
"Myndill",
"Mysterious Adventurer",
"Mysterious Old Man",
"Mysterious Stranger",
"Mysterious Stranger (Hallowed Sepulchre)",
"Mysterious Voice",
"Mysterious Watcher",
"Mystery figure",
"Naghead",
"Nakasa Jovkai",
"Nardah Banker",
"Nardok",
"Natalidae Shadum",
"Nathifa",
"Natural historian",
"Natural Historian (Mount Quidamortem)",
"Nature impling",
"Necrovarus",
"Ned",
"Ned (historical)",
"Neferti the Camel",
"Neil",
"Neite",
"Nellas",
"Nemishka",
"Nerdanel",
"Nesty",
"New Recruit Tony",
"Nexling",
"Nezikchened",
"Nia",
"Nicholas",
"Nick",
"Nickolaus",
"Nicoleta",
"Nieve",
"Nigel",
"Nigel (2013 Easter event)",
"Nightmare Zone lobby cow",
"Nikkie",
"Niles",
"Niloof",
"Nimloth",
"Nimrodel",
"Ninja impling",
"Nipper",
"Nirrie",
"Nisha",
"Nkuku",
"'No fingers'",
"Noctillion Lugosi",
"Noella",
"Nolar",
"Nomad",
"Noodle",
"Noon",
"Nora T. Hagg",
"Noranna Tytanin",
"Norman",
"Not Bob",
"Noterazzo",
"Novice",
"Nulodion",
"Numpty",
"Nung",
"Nurmof",
"Nurse Boubou",
"Nurse Emma Gentsy",
"Nurse Inn'Juree",
"Nurse Sarah",
"Nurse Wooned",
"Nylocas (A Night at the Theatre)",
"Nylocas (A Taste of Hope)",
"Nylocas Queen",
"Oaknock the Engineer",
"Oath Lord D'rows",
"Oathbreaker B'ats",
"Oathbreaker E'piws",
"Oathbreaker M'als",
"Obli",
"Observatory assistant",
"Observatory professor",
"Odd Mushroom",
"Odd Old Man",
"Odd Stone",
"Oddskull (NPC)",
"Odmar",
"Odovacar",
"Odysseus",
"Og",
"Ogre boat",
"Ogre guard",
"Ogre merchant",
"Ogre trader",
"Ogre trader (Dal)",
"Olaf Hradson",
"Olaf the Bard",
"Olbertus",
"Old crone",
"Old dwarf",
"Old man",
"Old man (Shayzien)",
"Old Man Ral",
"Old Man Yarlo",
"Oldak",
"Olivia",
"Ollie the Camel",
"Olmlet",
"Omart",
"Oneiromancer",
"Oobapohk",
"Oozing barrier",
"Operator",
"Oracle",
"Orange salamander (Hunter)",
"Ordan",
"Ork (Zanaris)",
"Orlando Smith",
"Ornate undead combat dummy",
"Oronwen",
"Oropher",
"Orophin",
"Orrvor quo Maten",
"Osian",
"Osman",
"Osman (The man who is not Osman)",
"Ospak",
"Osten",
"Osvald",
"Oswald",
"Oswallt",
"Other Half-Zombie",
"Otto Godblessed",
"Ouditor",
"Overcharged catalytic guardian",
"Overcharged elemental guardian",
"Overgrown cat",
"Owl",
"Oxi",
"Oziach",
"Oziach (2021 Halloween event)",
"Pagida",
"Painted One",
"Palum",
"Pandur Hosidius",
"Panning guide",
"Parrot",
"Parrots",
"Parroty Pete",
"Party gnome",
"Party Pete",
"Party Pete (2014 April Fools)",
"Patchy",
"Patrick",
"Patrolman",
"Patrolwoman",
"Paul (2019 Christmas event)",
"Pauline Polaris",
"Paws",
"Peaceful barbarian spirit",
"Peasant",
"Pebble",
"Peer the Seer",
"Peksa",
"Pelican",
"Penguin (Cold War)",
"Penguin display",
"Pennant",
"Pentyn",
"Penwie",
"Perdu",
"Perfect gold ore (Blast Furnace)",
"Perrdur",
"Perry",
"Pescaling Pax",
"Pet chaos elemental",
"Pet dagannoth prime",
"Pet dagannoth rex",
"Pet dagannoth supreme",
"Pet dark core",
"Pet general graardor",
"Pet k'ril tsutsaroth",
"Pet kraken",
"Pet kree'arra",
"Pet penance queen",
"Pet rock",
"Pet smoke devil",
"Pet snakeling",
"Pet zilyana",
"Peter",
"Peter (rabbit)",
"Petra Fiyed",
"Petrified Pete",
"Phabelle Bile",
"Phantuwti Fanstuwi Farsight",
"Pharaoh Kemesis",
"Phials",
"Phileas Rimor",
"Philipe Carnillean",
"Phillipa",
"Philop",
"Phingspet",
"Phluxia bat",
"Phoebe Kay",
"Phoenix",
"'Picarron' Pete",
"Pierre",
"Pieve",
"Pig",
"Pig Thing",
"Piglet",
"Pile of bones",
"Piles",
"Pilg",
"Piliar",
"Pillory Guard",
"Ping",
"Pious Pete",
"Pious Pete (20th Anniversary event)",
"Pipistrelle Draynar",
"Pirate (Catacombs of Kourend)",
"Pirate (Mos Le'Harmless)",
"Pirate Jackie the Fruit",
"Pirate Pete",
"PKMaster0036",
"Plague cow",
"Player character",
"Plough",
"Poison Salesman",
"Polar eagle",
"Polar kebbit",
"Polmafi Ferdygris",
"Pong",
"Pontak",
"Ponts the Bridgemaster",
"Poor looking man",
"Poor looking woman",
"Port Official",
"Port worker",
"Portal (Rune essence mine)",
"Portal of Death",
"Portobello",
"Possessed pickaxe",
"Possessed puppet",
"Postie Pete",
"Pouncer",
"Pox",
"Prael bat",
"Praistan Ebola",
"Prancer",
"Prayer tutor",
"Preacher",
"Preswylwyr Dall",
"Prickly kebbit",
"Priest (East Ardougne)",
"Priest (Goblin)",
"Priest (Sophanem)",
"Priest (West Ardougne)",
"Priestess Zul-Gwenwynig",
"Primula",
"Prince Ali",
"Prince black dragon",
"Prince Brand",
"Princess Astrid",
"Prison Pete",
"Prisoner",
"Prisoner (Darkmeyer)",
"Prissy Scilla",
"Private Paldo",
"Private Paldon",
"Private Pendron",
"Private Pierreb",
"Probita",
"Professor Gracklebone",
"Professor Imblewyn",
"Professor Manglethorp",
"Professor Oddenstein",
"Professor Onglewip",
"Progress hat",
"Prosecutor",
"Prospector Percy",
"Protest Leader",
"Protester",
"Psykk bat",
"Puffer Fish",
"Puffin",
"Pumpkin (2013 Rare Drops)",
"Pumpy",
"Purepker895",
"Purple partyhat (2013 April Fools)",
"Purple partyhat (2013 Rare Drops)",
"Purple Pewter Director",
"Purple Pewter Secretary",
"Pusskins",
"Pyramid block (Agility Pyramid)",
"Pyromancer",
"Quartermaster",
"Queen Ellamaria",
"Queen Sigrid",
"Queen Zyanyi Arkan",
"Quest Guide",
"Quiz Master",
"Qutiedoll",
"R0ck 5masher",
"R2t2pnsh0Ty",
"R4ng3rNo0b889",
"Rabbit (2014 Easter event)",
"Rabbit (2020 Easter event)",
"Rabbit (Castle Wars)",
"Rabbit Chef",
"Raccoon",
"Rachael",
"Radigad Ponfit",
"Radimus Erkle",
"Radu",
"Raeli",
"Raetul",
"Ragnar",
"Rakkar",
"Ramara du Croissant",
"Ramarno",
"Ramocean",
"Ranael",
"Randivor",
"Ranged combat tutor",
"Ranger",
"Ranger (Kebos Lowlands)",
"Ranger (medium)",
"Ranger (Shayzien)",
"Ranging Guild Doorman",
"Ranis Drakan",
"Rantz",
"Raqueel",
"Rashiliyia",
"Rasolo",
"Rassain",
"Rat Burgiss",
"Rauborn",
"Raulyn",
"Raum Urda-Stein",
"Raven",
"Razmire Keelgan",
"Razor-backed kebbit",
"Razvan",
"Rebel Archer",
"Rebel Scout",
"Rebel Warrior",
"Recruiter",
"Recruiter (Wilderness Wars)",
"Red Axe Cat",
"Red Axe Director",
"Red Axe Secretary",
"Red fireflies",
"Red geist",
"Red h'ween Mask (2013 Rare Drops)",
"Red monkey",
"Red Panda",
"Red partyhat (2013 April Fools)",
"Red partyhat (2013 Rare Drops)",
"Red salamander (Hunter)",
"Red Sheep",
"Redbeard Frank",
"Reese",
"Reeso",
"Ref",
"Refugee",
"Regath",
"Regent",
"Reginald",
"Reinald",
"Reindeer hat (2013 Rare Drops)",
"Reinn",
"Reldak",
"Reldo",
"Relobo Blinyo (logs)",
"Remsai",
"Remus Kaninus",
"Renegade knight",
"Rennard",
"Researcher",
"Reshi",
"Resistance Fighter",
"Restless ghost",
"Restless Goat",
"Retired sailor",
"Rewards Guardian (Mage Training Arena)",
"Rhazien",
"Rhiannon",
"Rhoddwr Tan",
"Rhonen",
"Rhyfel",
"Richard (Ardougne)",
"Richard (Hosidius)",
"Richard (merchant)",
"Richard Flintmaul",
"Rick",
"Rick (2020 Halloween event)",
"Rick (Wizards' Tower)",
"Rick Turpentine",
"Rickety door",
"Rid",
"Rift guardian",
"Riki the sculptor's model",
"Rimae Sirsalis",
"Rind the gardener",
"Rionasta",
"Roachey",
"Roavar",
"Robert Boss",
"Robert O'Reilly",
"Robert the Strong",
"Robin",
"Robyn",
"Rock golem",
"Rocking chair (2021 Halloween event)",
"Rocky",
"Rod Fishing spot (anglerfish)",
"Rod Fishing spot (infernal eel)",
"Rod Fishing spot (lure, bait)",
"Roger",
"Rogue Guard",
"Rohak",
"Rokuh",
"Rolad",
"Rolayne Twickit (hard)",
"Romeo",
"Rometti",
"Romettini",
"Romily Weaklax",
"Rommik",
"Ron Gadderanks",
"Ronan",
"Rooster (Nigel)",
"Root",
"Rory",
"Rosie",
"Rosie (pixie)",
"Ross",
"Ross and Ben",
"Rowdy dwarf",
"Roy",
"Roy jr.",
"Royal Guard",
"Ruantun",
"Rubber chicken (2013 Rare Drops)",
"Ruby harvest",
"Rufus",
"Rug Merchant",
"Rug Station Attendant",
"Runa",
"Runite Minor",
"Runite ore (Blast Furnace)",
"Runolf",
"Runvastr",
"Rupert the Beard",
"Saba",
"Saba (2014 April Fools)",
"Sabeil",
"Saboteur",
"Sabre-toothed kebbit",
"Sabre-toothed kyatt",
"Sabreen",
"Sacrifice",
"Sadwrn",
"Saeros",
"Saeth",
"Safalaan Hallow",
"Safta Doc",
"Sagira",
"Sailor",
"Sailor (Ruins of Unkah)",
"Salenab",
"Salgant",
"Sam",
"Sam (barmaid)",
"Sam (Christmas 2016)",
"Sam (merchant)",
"Sammy Servil",
"San Fan",
"Sand storm",
"Sandicrahb",
"Sandwich lady",
"Sandwich lady (2014 April Fools)",
"Sandy",
"Sanfew",
"Sani Piliu",
"Saniboch",
"Santa",
"Santa (2021 Christmas event)",
"Santa (historical)",
"Santa hat (2013 Rare Drops)",
"Santa's bodyguard",
"Santa's throne (2021 Christmas event)",
"Santiri",
"Sapphire glacialis",
"Saradominist recruiter",
"Sarah",
"Sarah (Mahogany Homes)",
"Sarah (Piscarilius)",
"Sarah (Port Phasmatys)",
"Sarble",
"Sarius Guile",
"Saro",
"Sassilik",
"Sassilik (Jatizso)",
"Savage bird",
"Savant",
"Sawmill operator",
"Sawmill Operator (Prifddinas)",
"Sbott",
"Scared skavid",
"Scarg",
"Scavvo",
"Schoolboy",
"Schoolgirl",
"Scorpia's offspring",
"Scout (2013 Goblin Invasion)",
"Scout (Falador)",
"Scout (Shantay Pass)",
"Scout (Tai Bwo Wannai)",
"Scout (Tree Gnome Stronghold)",
"Scrubfoot",
"Scruffy",
"Scythe (2013 Rare Drops)",
"Sea slug (race)",
"Sea slugs display",
"Sea Troll General",
"Seaman Lorris",
"Seaman Morris",
"Seaman Thresnor",
"Secretary",
"Security Guard",
"Seddu",
"Seer",
"Selena",
"Selene",
"Selim",
"Seravel",
"Sergeant",
"Sergeant (Kebos Lowlands)",
"Sergeant Damien",
"Sergeant Mossfists",
"Sergeant Ricardo",
"Sergeant Sambur",
"Sergeant Slimetoes",
"Sergiu",
"Servant (ScapeRune)",
"Servery assistant",
"Seth",
"Seth Groats",
"Shade Spirit",
"Shadowy figure",
"Shaeded Beast",
"Shamus",
"Shanomi",
"Shantay",
"Shantay Guard (Ruins of Unkah)",
"Shanty Claws",
"Sharimika",
"Shark (ocean)",
"Shayda",
"Shayzien Infiltrator",
"Sheep",
"Sheep (2021 Birthday event)",
"Sheep (Big Cats & WWF)",
"Sheep (Castle Wars)",
"Sheep (penguins)",
"Sheep (Zanaris)",
"Sheepdog",
"Sherlock",
"Sheryl",
"Shield master",
"Shilop",
"Shiratti the Custodian",
"Shop assistant (Al Kharid)",
"Shop assistant (Edgeville)",
"Shop assistant (Falador)",
"Shop assistant (Lumbridge)",
"Shop assistant (Musa Point)",
"Shop assistant (Rimmington)",
"Shop assistant (Varrock Swordshop)",
"Shop assistant (Varrock)",
"Shop keeper (2020 Easter event)",
"Shop keeper (Al Kharid)",
"Shop keeper (Combat Training Camp)",
"Shop keeper (Edgeville)",
"Shop keeper (Falador)",
"Shop keeper (Fossil Island)",
"Shop keeper (Lumbridge)",
"Shop keeper (Musa Point)",
"Shop keeper (Port Khazard)",
"Shop keeper (Rimmington)",
"Shop keeper (The Warrens)",
"Shop keeper (Varrock Swordshop)",
"Shop keeper (Varrock)",
"Shura",
"Siamun",
"Sian",
"Sid",
"Siegfried Erkle",
"Sigbert the Adventurer",
"Sigismund",
"Sigli the Huntsman",
"Sigmund",
"Sigmund and Zanik",
"Sigmund The Merchant",
"Signy",
"Sigurd",
"Sil'as Dahcsnu",
"Silk merchant",
"Silk trader",
"Silver Cog Director",
"Silver Cog Secretary",
"Silver merchant",
"Silver ore (Blast Furnace)",
"Simon",
"Simon (Piscarilius)",
"Simon Templeton",
"Simona",
"Sin Seer",
"Sinclair Guard dog",
"Sinco Doar",
"Sinister Stranger",
"Sir Amik Varze",
"Sir Bedivere",
"Sir Gawain",
"Sir Kay",
"Sir Kuam Ferentse",
"Sir Lancelot",
"Sir Lucan",
"Sir Palomedes",
"Sir Pelleas",
"Sir Percival",
"Sir Prysin",
"Sir Rebral",
"Sir Ren Itchood",
"Sir Renitee",
"Sir Spishyus",
"Sir Tiffy Cashien",
"Sir Tinley",
"Sir Tristram",
"Sir Vyvin",
"Sir Vyvin (2021 Christmas event)",
"Sirsal Banker",
"Sister Aseret",
"Sister Naoj",
"Sister Salohcin",
"Sister Scarophia",
"Sister Senga",
"Sister Sevi",
"Sister Soul Jar",
"Sister Toen",
"Sister Yram",
"Sithik Ints",
"Skavid",
"Skeletal thrall (beta)",
"Skeleton (2018 Halloween event)",
"Skeleton (Enakhra's Lament)",
"Skeleton (Malignius Mortifer)",
"Skeleton (Wrath Altar)",
"Skeleton mage (Malignius Mortifer)",
"Skeleton outfit (2013 Rare Drops)",
"Skippy",
"Skotos",
"Skrach Uglogwee",
"Skulgrimen",
"Skuli Myrka",
"Skullball",
"Skullball Boss",
"Skullball Trainer",
"Skully",
"Slagilith",
"Slave (daeyalt essence mine)",
"Slave (Mourner Tunnels)",
"Slave (Underground Pass)",
"Sleeping Monkey",
"Sleepwalker",
"Slieve",
"Slim Louie",
"Slippers",
"Sloane",
"Slug Hemligssen",
"Slug Prince",
"Small ninja monkey",
"Small zombie monkey",
"Smellytoes",
"Smiddi Ryak (hard)",
"Smith",
"Smithing apprentice",
"Smoggy",
"Smokin' Joe",
"Smolcano",
"Snail display",
"Snailneck",
"Snake (The Asp & Snake Bar)",
"Sneaky undead fowl",
"Snow (Wintertodt)",
"Snow Sprite",
"Snowball (2021 Christmas event)",
"Snowflake",
"Snowman",
"Snowy knight",
"Soldier (Battlefront)",
"Soldier (Burthorpe)",
"Soldier (Death Plateau)",
"Soldier (Dragon Slayer II)",
"Soldier (Kebos Lowlands)",
"Soldier (Lizardman Canyon)",
"Soldier (recruits)",
"Soldier (Shayzien, historical)",
"Soldier (The Cloak and Stagger)",
"Solihib",
"Solztun",
"Sophanem Guard",
"Sophia Hughes",
"Sorceress",
"Sorcha",
"Sorin",
"Sorrn",
"Soul",
"Sourhog (A Porcine of Interest)",
"Spang",
"Spawn (lizardman shaman)",
"Spectator",
"Sphinx",
"Spice seller",
"Spider (Hallowed Sepulchre)",
"Spider (Morytania)",
"Spined larupia",
"Spirit (2018 Halloween event)",
"Spirit Angler",
"Spirit Angler (Reward pool)",
"Spirit of Scorpius",
"Spirit of Zadimus",
"Spirit pool",
"Spit goblin",
"Spotted kebbit",
"Spria",
"Spring Elemental",
"Squire",
"Squire (Camelot)",
"Squire (Crypt)",
"Squire (Intermediate)",
"Squire (Novice)",
"Squire (Veteran)",
"Squire (Void Knights banker)",
"Squire (Void Knights general store)",
"Squire (Void Knights magic shop)",
"Squire (Void Knights ranged shop)",
"Squire (Void Knights smith)",
"Squire (Void Knights)",
"Squirrel",
"Squirrel (Fossil Island)",
"Squirrel (troll)",
"Squirrel (Weiss)",
"Sraracha",
"Stag (Big Cats & WWF)",
"Stanford",
"Stankers",
"Star Sprite",
"Steve",
"'Sticky' Sanders",
"Stonemason",
"Stonemason (Sophanem)",
"Storm Cloud",
"Storm cloud (Zanaris)",
"Strange Device (Tale of the Righteous)",
"Strange Old Man",
"Strange plant",
"Strange watcher",
"Stranger (In Search of the Myreque)",
"Straven",
"Stray dog",
"Street urchin",
"Strolgrum",
"Strong catalytic guardian",
"Strong elemental guardian",
"Strong Ronny",
"Student",
"Stuliette",
"Stumpy",
"Stunted demonic gorilla",
"Styrmir",
"Summer Elemental",
"Summoned Soul",
"Sune",
"Superior ghostly thrall",
"Superior skeletal thrall",
"Superior zombified thrall",
"Supreme Commander",
"Surgeon General Tafani",
"Surma",
"Surok Magis",
"Survival Expert",
"Suspect",
"Suspicious crate",
"Svidi",
"Swamp creature",
"Swamp lizard (Hunter)",
"Swamp Priest",
"Swamp Toad",
"Swan",
"Swarm",
"Swarm (random event)",
"Sweeper",
"Sweetflies",
"Swensen the Navigator",
"Sylas",
"Taiman",
"Talia",
"Tamayu",
"Tamble",
"Tangleroot",
"Tanner (Crafting Guild)",
"Tanya",
"Tanya (Slepe)",
"Taper",
"Tar Monster",
"Tarfol quo Maten",
"Taria",
"Tarik",
"Tarn",
"Tarquin",
"Tassie Slipcast",
"Tati",
"Tatie",
"Tau",
"Taxidermist",
"Taylor",
"Tayten",
"Tea Seller",
"Teacher and pupil",
"Ted Rehnison",
"Tegdak",
"Tegid",
"Telekinetic Guardian",
"Tempoross",
"Tenzing",
"Teodor",
"Terrorbird display",
"Terrorchick gnome",
"Thakkrad Sigmundson",
"The 'Wedge'",
"The Collector",
"The Disappointing Gelt",
"The Face",
"The Fisher King",
"The Great Guardian",
"'The Guns'",
"The Illusive",
"The Lady of the Lake",
"The Monkey's Aunt",
"The Monkey's Uncle",
"The Nightmare",
"The Sage",
"The Shaikahan",
"Thessalia",
"Thias Leacke",
"Thidrolda",
"Thing under the bed",
"Thingol",
"Thirus",
"Thistle (Troll)",
"Thomdril",
"Thora",
"Thora the Barkeep",
"Thordur",
"Thorgel",
"Thorkel Silkbeard",
"Thormac",
"Thorodin",
"Thorodin (Rellekka)",
"Thorvald the Warrior",
"Thrander",
"Thumpy",
"Thurgo",
"Thyria",
"Tiadeche",
"Ticket dwarf",
"Ticket goblin",
"Ticket Merchant",
"Tide",
"Tiles",
"Tilt",
"Tim",
"Timallus",
"Timble",
"Timfraku",
"Tin ore (Blast Furnace)",
"Tina",
"Tindar",
"Tindel Marchant",
"Tinsay",
"Tinse Torpe",
"Tiny tempor",
"Tirrie",
"Tjorvi",
"Toban",
"Toby",
"Tolna",
"Tom",
"Tomas Lawry",
"Tombar",
"Tommy 2-times",
"Tool Leprechaun",
"Tool Leprechaun (Larry)",
"Toothy",
"Topsy",
"Torbrund",
"Torfinn",
"Torrcs",
"Torrell",
"Tostig",
"Tower Advisor",
"Tower Mage",
"Town Crier",
"Town Guard",
"Toy boatman",
"Tracker gnome 1",
"Tracker gnome 2",
"Tracker gnome 3",
"Trade Referee",
"Trader (The Blue Opal)",
"Trader (The Brown Engine)",
"Trader (The Green Gemstone)",
"Trader (The Purple Pewter)",
"Trader (The Red Axe)",
"Trader (The Silver Cog)",
"Trader (The White Chisel)",
"Trader (The Yellow Fortune)",
"Trader Crewmember",
"Trader Stan",
"Trader Sven",
"Tragacanth",
"Trainee Guard",
"Trainer Nacklepen",
"Tramp",
"Tramp (pillory)",
"'Transmute' The Alchemist",
"Travelling merchant",
"Traxi",
"Treacle",
"Treasure fairy",
"Trefaji",
"Treus Dayth",
"Treznor",
"Tribal Weapon Salesman",
"Tristan",
"Trobert",
"Trogen Konungarde",
"Troll (2014 April Fools)",
"Troll child",
"Troll father",
"Troll mother",
"Tropical wagtail",
"Trossa",
"Trufitus",
"Tsunami",
"Turael",
"Turbogroomer",
"Turgall",
"Turgok",
"Turgon",
"Turkey",
"Tutab",
"Twiggy O'Korn",
"Two-pints",
"Tyke",
"Tynan",
"Tyras guard (Catapult)",
"Tyss",
"TzHaar-Hur-Koz",
"TzHaar-Hur-Lek",
"TzHaar-Hur-Rin",
"TzHaar-Hur-Tel",
"TzHaar-Hur-Zal",
"TzHaar-Ket-Keh",
"TzHaar-Ket-Rak",
"TzHaar-Ket-Yil",
"TzHaar-Ket-Zuh",
"TzHaar-Mej",
"TzHaar-Mej-Bal",
"TzHaar-Mej-Dir",
"TzHaar-Mej-Jal",
"TzHaar-Mej-Kah",
"TzHaar-Mej-Roh",
"Tzrek-jad",
"Ug",
"Uglug Nar",
"Ulfric",
"Ulifed",
"Ulina",
"Ulizius",
"Ulsquire Shauncy",
"Undead combat dummy",
"Undead cow",
"Undead tree",
"Undor",
"Unferth",
"Unicorn (Underground Pass)",
"Unicorn1337Kilr",
"Ur-lun",
"Ur-meg",
"Ur-pel",
"Ur-taal",
"Ur-tag",
"Ur-vass",
"Ur-zek",
"Urbi",
"Uri",
"Usi",
"Utrec",
"Uurrak quo Narga",
"Uwogo",
"Vaeringk",
"Vaire",
"Valaine",
"Valantay Eppel (medium)",
"Valdez",
"Valentin Rasputin",
"Valentina Diaemus",
"Valeria",
"Vallessia Dracyula",
"Vallessia von Pitt",
"Vampyre Juvenile (Ver Sinhaza)",
"Vampyressa van Von",
"Vampyric hound",
"Vampyrus Diaemus",
"Vanescula Drakan",
"Vanessa",
"Vanligga Gastfrihet",
"Vannah",
"Vannaka",
"Vanstrom Klause",
"Varrian Sobak",
"Vasile",
"Vasquen",
"Veliaf Hurtz",
"Velorina",
"Velrak the explorer",
"Venenatis spiderling",
"Veos",
"Veos' Client",
"Verak",
"Vermundi",
"Veronica",
"Vertida Sefalatis",
"Verzik Vitur",
"Vestri",
"Vet'ion jr.",
"Victor",
"Viggora",
"Vigr",
"Vigroy",
"Villager",
"Villia",
"Violetta Sanguine",
"Vixen",
"Vlad Bechstein",
"Vlad Diaemus",
"Vladimir",
"Voice of Yama",
"Void Knight",
"Void Knight (Pest Control)",
"Volf Olafson",
"Von van Von",
"Vonnetta Varnis",
"Vorki",
"Vormar Vakan",
"Vornas quo Maten",
"Vortas quo Keran",
"Vritra",
"Vulcan Orvoros",
"Vyre Orator",
"Vyrelady",
"Vyrelord",
"Wagchin",
"Wally",
"Wanderer",
"Wandering impling",
"War ship (2013 Rare Drops)",
"Warrior (Lost City)",
"Watchtower Wizard",
"Watson",
"Waydar",
"Waymottin",
"Wayne",
"Wayne (2021 Christmas event)",
"Weak catalytic guardian",
"Weak elemental guardian",
"Weapon poison salesman",
"Weast side49",
"Weird Old Man",
"Weird snake.",
"Wemund",
"Wengra quo Sihar",
"Werewolf (Darkmeyer)",
"Werewolf (Sins of the Father)",
"Werewolf (Werewolf Agility Course)",
"Wesley",
"Weve",
"White Chisel Director",
"White Chisel Secretary",
"White partyhat (2013 April Fools)",
"White partyhat (2013 Rare Drops)",
"White rabbit",
"Wild kebbit",
"Will o' the wisp",
"William",
"Willow (Below Ice Mountain)",
"Wilough",
"Wily cat",
"Winelda",
"Wingstone",
"Winkin",
"Winter Elemental",
"Winter Soldier",
"Wintertoad",
"Wintumber tree (2013 Rare Drops)",
"Wise Old Man",
"Wise Old Man (2014 April Fools)",
"Wise Old Man (2022 Birthday event)",
"Wiskit",
"Wistan",
"Witch",
"Witch (Lensig)",
"Witch's cat",
"Witchaven villager",
"Wizard (Arceuus)",
"Wizard (Last Man Standing)",
"Wizard (Lost City)",
"Wizard (Watchtower)",
"Wizard Akutha",
"Wizard Cromperty",
"Wizard Distentor",
"Wizard Frumscone",
"Wizard Grayzag",
"Wizard Jalarast",
"Wizard Mizgog",
"Wizard Persten",
"Wizard Sinina",
"Wizard Traiborn",
"Wolfbone",
"Woman (Wanted!)",
"Woman-at-arms (hard)",
"Wood Dryad",
"Wooden ducks",
"Woodsman tutor",
"Worker",
"Workman",
"Workman (Digsite)",
"Workman (wheelbarrow)",
"Worried Baker",
"Wounded soldier",
"Wurbel",
"WWF conservationist",
"Wydin",
"Wyson the gardener",
"Wyson the gardener (2021 Christmas event)",
"Wyvern display",
"Xamphur",
"Xarpus",
"Xi plzPetDogz xiX",
"Xorrah quo Sihar",
"Yanes",
"Yanni Salika",
"Yarsul",
"Yeldive",
"Yellow Fortune Director",
"Yellow Fortune Secretary",
"Yellow geist",
"Yellow partyhat (2013 April Fools)",
"Yellow partyhat (2013 Rare Drops)",
"Yellow Sheep",
"Yellow Snow",
"Yenrab",
"Ymladd",
"Yo-yo (2013 Rare Drops)",
"Yohnus",
"Young 'un",
"Young impling",
"Youngllef",
"Yrsa",
"Ysbeid",
"Ysgawyn",
"Ystwyth",
"Yulf Squecks",
"Yusuf",
"Zaff",
"Zahra",
"Zahur",
"Zahwa",
"Zambo",
"Zamorakian Acolyte",
"Zamorakian recruiter",
"Zanaris choir",
"Zandar Horfyre",
"Zanik",
"Zapper",
"Zaros (2014 April Fools)",
"Zavistic Rarve",
"Zealot",
"Zeke",
"Zeke (2021 Birthday event)",
"Zenesha",
"Zenkog",
"Zimberfizz",
"Zombie (2005 Halloween event)",
"Zombie (Malignius Mortifer)",
"Zombie (Surprise Exam)",
"Zombie Head (2005 Halloween event)",
"Zombie head (2013 Rare Drops)",
"Zombie monk",
"Zombie protester",
"Zombie Thrall (beta)",
"Zoo keeper",
"Zooknock",
"Zorgoth",
"Zul-Aniel",
"Zul-Areth",
"Zul-Cheray",
"Zul-Gutusolly",
"Zul-Onan",
"Zul-Urgish",
"Zygomite"] 